server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://54.180.138.215:3306/polling?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
    username: devmysql
    password: Devmysql1234!
    initialization-mode: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG


